import { Button, IconButton } from "@/components/Styles/Buttons";
import styles from "@/styles/Home.module.css";
import { GlobalStyles } from "@/styles/globalStyle";
import { darkTheme, lightTheme } from "@/styles/theme";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";
import { parseCookies, setCookie } from "nookies";
import { BsList } from "react-icons/bs";
import { ThemeProvider } from "styled-components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { theme } = parseCookies();
  const router = useRouter();

  const themeToggler = () => {
    setCookie(null, "theme", theme === "light" ? "dark" : "light", {
      path: "/",
    });
    router.replace("/");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ThemeProvider theme={theme === "light" ? lightTheme : darkTheme}>
          <GlobalStyles />
          <Button onClick={themeToggler}>Switch Theme</Button>{" "}
          <Button>Xanadu</Button>
          <IconButton>
            <BsList />
          </IconButton>
          <IconButton size="lg" onClick={themeToggler}>
            <BsList />
          </IconButton>
        </ThemeProvider>
      </main>
    </>
  );
}
