'use client';

import { Navbar } from '@/components/Navbar';
import styles from '@/styles/Home.module.css';
import { GlobalStyles } from '@/styles/globalStyle';
import { darkTheme, lightTheme } from '@/styles/theme';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { parseCookies } from 'nookies';
import { ThemeProvider } from 'styled-components';
import StyledComponentsRegistry from '../lib/registry';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { theme } = parseCookies();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <StyledComponentsRegistry>
          <ThemeProvider theme={theme === 'light' ? lightTheme : darkTheme}>
            <GlobalStyles />
            <Navbar />
          </ThemeProvider>
        </StyledComponentsRegistry>
      </main>
    </>
  );
}
